#+TITLE:读书记录
* 经典文学
** 《蝇王》 0x							  :(英)威廉·戈尔丁:
1. 短评
   翻译不喜欢（上海译文出版社 2009-10）。
2. 时间
   <2016-11-24 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/4125911/
** 《恐惧》 4x 							 :[奥]斯蒂芬•茨威格:
1. 短评
   与《一个陌生女人的来信》有着相同爽快的阅读体验，很好奇茨威格如何能够写女人写的入木三分。
2. 读后感
   小说的女主角与情人偷情被发现而受到情人“女友”的威胁和敲诈，因而陷入了深深的恐惧之中，甚至想要结束自己的生命，结果最后发现是丈夫设下的局。

   纵然我们很少有人有偷情被发现这样的经历，这份类似的恐惧感依然深深地抓住了我的心，我们或多或少都曾处于过这样的境地，很多时候这份恐惧比事实能对我们造成的伤害还要大的多。

   对于为何会产生这样的行为，小说进行了一些探讨。女主说这种恐惧是出于对最亲密之人的爱，这样的说法多少有些往自己脸上贴金的味道。而在我看来，这种情绪出现的最大原因就是我们很多时候都不能或者说不敢去承受一件事情可能带来的后果，至于不想伤害别人，不过是软弱的借口而已。
3. 完成时间
   <2016-11-30 周三>
4. 资源
   + 豆瓣：https://book.douban.com/subject/10563555/
** 《动物农场》5*                                                :【英】乔治·奥威尔:
1. 读后感
   以动物拟人，虚拟出一个逐步崩坏的世界，这本书或许没有作者的《1984》那么残酷，内涵上或许还要更深一筹。

   论集权政府如何产生，当一部分人在智力或者说信息上领先其他人时，他们便有了成为领导的先决条件，而成为领导阶层之后对下层人民的统计地位必将唆使他们更进一步的想要统治上层阶级的其他同类，若干个有这样想法的人之间就会发生斗争，然后胜利的那个群体会成为统治者，如果那个统治者太过强大，便会产生集权。

2. 时间
   2013-05-27

3. 豆瓣
   https://book.douban.com/subject/2035179/
* 现代文学
** 《没有人给他写信的上校》4x					    :(哥伦比亚)加西亚·马尔克斯:
1. 读后感
   抛去魔幻现实主义的繁华，淳朴真实的马尔克斯依然有触动人心的力量。
2. 资源
   豆瓣：[[https://book.douban.com/subject/20392523/]]
3. 时间
   开始时间：<2016-11-29 周二>
   结束时间：<2016-11-30 周三>
** 《一个背叛日本的日本人》2x					    :(日)松本清张:
    1. 短评       
    2. 读后感
       说实在的，我没有从这本小说中获得什么有用的体会。悬念被标题剧透地丧心病狂，毫无紧张感和悬念感，整体的人物塑造也很苍白，读完后没有哪位人物给我留下了很深的印象，剧情也安排地毫无张力。
    3. 资源
       豆瓣：https://book.douban.com/subject/6848987/
    4. 其他
       原名：《球形的荒野》
*** 《手机里的男朋友 : 方慧首部短篇小说集》                            :方慧:
1. 短评
   开头弃，节奏和文笔不能吸引我。
2. 资源
   豆瓣：https://book.douban.com/subject/26647727/
*** 《我就要你好好的（新版）》                                  :【英】乔乔·莫伊斯:
1. 短评
   爱情这种东西，很多时候并没有我们想的那么有力。
2. 资源
   豆瓣：https://book.douban.com/subject/26683858/
** 《地底三万尺》4*                                                    :朱少麟:
1. 短评
   人心何止三万尺，每一章都会让我想得更加深入。河城的世界太过虚幻，削弱了结尾的张力扣一分。
2. 读后感
   读到这本书完全是一个意外，一来名字听起来很有我喜欢的奇幻风格，二来豆瓣上的评分也颇为不错。当然实际读下来倒也没有辜负我的期待。
   开场首先就出现了一个很科幻的设定，一个各种边缘人士的收容所——河城，这让我觉得这会是一本科幻小说，而高分的科幻小说，想来是不会让我失望的。实际读下来却完全不是那么一会事，几乎没有任何科幻的元素，反而现实地有些不真实，你会真切地感受到他们和我们就处于同一个时代，只不过处在了一个不同的国家。
   小说视角的展开也很有意思，每一章都有一个主角，然后其他人会出现在这个人的故事中，这个世界也就很自然地一点一点清晰了起来。
3. 时间
   <2016-12-05 周一>
4. 资源
   豆瓣：https://book.douban.com/subject/6863827/
5. 笔记
   + 摘抄：人们只以为我趾高气扬，却没有一个人能够明了，我有多么不喜欢这份工作，不喜欢的程度，逼得我曾经像个厌恶上学的儿童一样，凭空捏造出许多病痛：胃溃疡、肝炎、骨刺、肺痨，不管是什么顽疾都好，只要能让我顺利调离河城。 因为郁闷的缘故，我所谎称的各种病况竟然一一成真，谁都看出来我整天心悸头疼，我渐渐厌倦食物，接着厌倦治疗，到末了厌倦泪水，厌倦笑容也厌倦阳光。 错误的选择如同病灶，枯萎的是人的思想。
     感想：
   + 摘抄：善恶是互相牵扯不清的，没有人真正罪恶，也没有人完全无辜，世界就像个大矿坑人人互相挖掘，所得仅只是碎屑，如何界定是非？
   + 摘抄：这种状况最奥妙，就因为事态已经糟糕到不可能更糟糕，所以反而没道理不解除警报，让自己彻底放松心情。关于放轻松，我的另一个朋友秃鹰有句话诠释得最好，他说：“当你已经平摆在地上，你就不可能再跌倒。”
   + 摘抄：这就是重点，人们看的是表面，人们给别人看的也是表面，没有人能真正认识另一个人，人们要明快的答案，不要听你慢慢细诉衷肠，你最好身份高尚，再不济也要模样讨喜。
   + 摘抄：光阴是一条地下污水道，你只能顺着它往前漂，一路上搀进来许多种味道，你就被浸得面目全非，在这边只有增加没有减少，世界从千万个方向朝你冲过来渗进你，谁也躲不了。没有脏不脏的问题，如果你知道你的源头，只是人家的一个马桶，或是一个排水口，你遭受很多次碰撞，你弄得全身都是伤，还是不停往前漂，你以为总有一天你到得了什么地方，你以为尽头会有光，实话告诉你吧，那边是一个更大的垃圾处理场。
   + 摘抄：他慷慨送给这世界许多富含哲理、听起来又很悲哀的佳句，“走路时一连串的防止跌倒”，“每一次睡眠都是为了与明天保持距离”。总而言之，生得太晚是我们的错，所以只配捡到秃鹰又老又丑。
   + 摘抄：再不可爱的人也不时会感染爱情，通常不致命，只是会犯一些痴狂，然后不停地受一点伤。
   + 摘抄：少女真正需要的是心情、是幻想，藏在心里的秘密偶像有如蛋白质，流行打扮杂志足以提供碳水化合物，别人的注视能滋生矿物质，满脑子罗曼史就等于维生素。
   + 摘抄：一定要分类的话，我会说大部分的人都是一般垃圾，只是你自己不会承认而已，你只会觉得自己很有价值，你很努力，你妈的谁不努力？你努力在掩盖，让自己看起来还不算失败，事实上你可有可无，这就是一般垃圾的特色，你吃不了半点苦，你定期发愤图强却连自己肚皮的脂肪也对付不了。
   + 摘抄：看到一长串的你怎样你怎样，就像看自己一样，我那么努力的就是为了活成一个优秀合格的一般垃圾，我自私，我贪婪，我说谎成性，我对自己真的很失望，我装模做样，就连现在写这些字的时候可能也还是在装模作样，整整一页半的文字每一个都写尽我的样貌，还真是坦白赤裸的可怕。
   + 摘抄：一切垃圾都是人的衍生物，只因为人太迂回，太不直接，太无法面对…你自己就是一大盒圣诞礼物，外头裹上漂亮得不得了的包装；拆开包装，是坚硬外壳；褪去外壳，是柔软衬护；剥下衬护，是浮夸修饰；揭掉修饰，是琐碎点缀；抹掉点缀，是怯生生的、一个无法曝光的，你。 总结：与人无关的，不曾被人拥有过的东西，也不会成为垃圾。
** 《漫长的中场休息》                                             :[美] 本·方登:
1. 短评
   个人感觉电影比小说更合我胃口，小说略显纷乱了一点。
2. 时间
   <2016-12-08 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/26890281/
** 《龙文身的女孩》4*                                            :[瑞典] 斯蒂格·拉森:
1. 短评
   比电影细腻，但就没有电影紧凑，各有千秋。
2. 时间
   <2016-12-09 周五>
3. 资源
   豆瓣：https://book.douban.com/subject/4292149/
 
** 《玩火的女孩》4*                                            :[瑞典] 斯蒂格·拉森:
1. 短评
   比第一部精彩，故事发展悬念迭生，背景故事渐渐展开的写法引人入胜，结局稍显离奇降低了冲击力。
2. 时间
   end：2016-12-12
3. 资源
   豆瓣：https://book.douban.com/subject/4934552/
** 《我的朋友X》3*                                                 :(丹麦)哈瑟姆:
1. 短评
   豆瓣上记录的第一本书，还记得那时还有时会去shopping mall四楼的书店站着看书，是因为什么？不太记得。犹记得这是一个人通过宗教获得救赎的故事，男主人公做了很多错事，知道某天家里突然出现一个人，对他进行引导，让他走上正确的道路，而这个人又不是真人，而是一个精神化的引导者，或者说“耶稣”。
   
   但是这本小说多少给人一种宣扬基督教的意味，耶稣为什么出现？不知道。“我”如何被感化？也不甚清楚。我相信宗教拥有很强大的力量，但我并不认为这本书说清了这种力量。
2. 时间
   2012-08-17
3. 豆瓣
   https://book.douban.com/subject/10428361/
** 《活着》5*                                                           :余华:
1. 短评
   “活着”，这两个字足以说明一切。福贵年少家境殷实，却不知珍惜染上赌博的毛病，不久输光了家产，之后还经历了被拉壮丁、大跃进等一系列事情，亲人也一个接一个不幸过世，最后只剩他和一头老黄牛相依为命，却仿佛带上了一种看透世事的沧桑。
   
   当年在地铁上，读着这本书，险些坐过了站，鼻子一直发酸，一开始福贵染上赌博等习性时，我是不齿的，但随着故事的发展，不幸的事情一件接一件的发生在他身上，我却莫名的恨他不起来。生活对他一直很苛刻，而他一直没有放弃地坚强地活着。他不聪明、不会钻营、没有文化也没有特殊的才能，但他依然努力地活着。这似乎也是许许多多中国人共同的哲学思维，活着，只是活着，很多时候就足够了。

2. 时间
   end：2013-05-27

3. 豆瓣
   https://book.douban.com/subject/1082154/
** 《直捣蜂窝的女孩》4*                                        :[瑞典] 斯蒂格·拉森:
1. 短评
   法庭审判酣畅淋漓，善恶有报大快人心。
2. 资源
   豆瓣：https://book.douban.com/subject/5993310/
** 《怪屋女孩》2*                                              :[美] 兰萨姆·里格斯:
1. 短评
   想着电影有我喜欢的伊娃格林就先看书，结果大概是小学三年级前的读物的水平，除了时光圈的设定其他真的乏善可陈。
2. 时间
   2016-12-19
3. 资源
   豆瓣： https://book.douban.com/subject/26868923/
** 《太阳黑子》3*                                                      :须一瓜:
1. 短评
   小说本身构思还算真实，奈何文笔有限，描写的人物既空洞又不合理，浪费了一个好题材。
2. 时间
   end：2016-12-22
3. 资源
   豆瓣：https://book.douban.com/subject/4799445/
4. 摘抄
   1) 我越来越不喜欢夜深人静，这里，静得可以听到高空里高压线芯里电子疯跑的声音，我没有它的形容词，也可能不是，就是时间本身的声音。真正的时间的声音。那声音有点像白天里，你把手掌虚窝在耳边听到的那种声音，空渺辽阔,极其飘虚，连接着千万年前，多听了你觉得自己比一缕丝线一缕烟还要细，听了想哭啊。
      感想：时间的声音，是个很感性的概念，我们或多或少都感受过，但很少有人能像作者那样表达出来，更重要的是，表达地很美。
   2) 现在的人心太坏了。他们心中没有准绳、没有神明。他们虽然没有杀人放火，没有烧杀抢劫，可是，心里面堆满了蛆虫一样的恶，贪婪、自私……又因为这些恶，为法律所不察，而且人人有份，所以，这世上，你几乎找不到一颗敬畏之心，愧疚之心，懊悔之心。这种人一生乏善可陈、邪恶满盈、死不悔悟，可是心安理得，他们在法律边缘糟蹋这道德，毒化着空气。这才是真正的罪人。哪怕失足大错，只要知罪懂错，用一生来赎罪，就是神会宽恕的人。
      感想：无论身处何时何处，都应该心怀敬畏。

** 《你的名字》0*                                                   :[日]新海诚:
1. 短评
   电影优秀，小说圈钱。
2. 时间
   end：<2016-12-15 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/26904824/
* 网络文学
** 《贩罪》0x                                                          :三天两觉:
1. 读后感
   三天两觉有伊坂幸太郎的气质,可惜文笔和格局上还跳脱不了网文的窠臼。
2. 资源
   豆瓣：https://book.douban.com/subject/26863353/
3. 时间
   开始时间：<2016-11-29 周二>
   结束时间：<2016-11-29 周二>
** 《手机里的男朋友》0*                                                 :方慧:
1. 短评
   语言和节奏方面不能吸引我，开头弃。
2. 时间
   <2016-11-23 周三>
3. 资源
   豆瓣：https://book.douban.com/subject/26647727/
** 《琥珀之剑》4*                                                       :绯炎:
1. 短评
   设定出彩，奈何规模铺展开后作者的把握能力明显不足，不过该热血的地方还是很热血的。
2. 时间
   end：<2017-01-04 周三>
3. 资源；
   豆瓣：https://book.douban.com/subject/20425356/
** 《龙族》0*                                                           :江南:
*** 短评
文笔太差，感觉似乎比此间的少年还要差。
*** 时间
end：<2017-01-06 周五>
*** 资源
豆瓣：https://book.douban.com/subject/4737329/
** 《奥术神座》3*
*** 短评
*** 摘抄
*** 读后感
* 推理悬疑
** 《替死者说话》0x                                                    :再见萧郎:
1. 短评
   开头弃，开头悬念设置的不错，但是文笔实在过于朴实，情节也显得很虚浮。
2. 时间
   开始时间：<2016-11-24 周四>
   结束时间：<2016-11-24 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/24698542/
** 《别和她说话》0x                                                     :遇瑾:
1. 短评
   开头弃，文笔差，心理学知识也不严谨。
2. 资源
   https://book.douban.com/subject/26434548/
** 《人偶为何被杀》2*                                              :（日）高木彬光:
1. 短评
   纪念一下，第一本完全看出诡计和凶手的小说，不过整体上真的蛮一般的。
2. 时间
   <2016-12-07 周三>
3. 资源：
   豆瓣：https://book.douban.com/subject/26422109/
** 《黑屋吊影》4*                                                    :(日)贵志祐介:
1. 短评
   有些地方气氛渲染相当出色，结尾女友的一段评论很有意思，不足在悬疑性稍差。
2. 时间
   end：2016-12-20
3. 资源
   豆瓣：https://book.douban.com/subject/25737792/
4. 读后感
   “用善意踏平的路，也会通向地狱。用恶意筑的墙，也可作为防波堤。”
   《黑屋吊影》，第4届日本恐怖小说大奖，读起来确实让人遍体生寒，最让人心生恐怖的地方，在于主角遇到的情况有可能在我们任何人身上发生，那位让人由衷恐惧的凶手，看起来不过是任何一个平常而普通的人。而动机只是骗取保险而已。
   可能是我从小生活条件都还可以，虽然谈不上锦衣玉食，倒也还算衣食无忧，所以我从来没有考虑过因为经济愿意恶意地伤害他人，我想这是我父母给我的极大的财富之一。
** 《蓝色虚拟空间》4*                                                :【美】迪弗:
*** 短评
最后的转折没想到，除此之外迪弗的书读起来总有一种无法言说的相似感
*** 时间
   end：2016-12-24
*** 资源
   豆瓣：https://book.douban.com/subject/1083761/
** 《金色梦乡》4*                                                   :[日]伊坂幸太郎:
*** 短评
伊坂幸太郎确实是天才，写作的天才。
*** 时间
end：<2017-01-01 周日>
*** 资源
豆瓣：https://book.douban.com/subject/5038409/
** 《猎豹》4*                                                      :[挪] 尤·奈斯博:
*** 短评
篇幅较长，节奏紧凑，转折稍微略显多了一些，文笔比《雪人》更成熟，震撼力却比雪人显得弱了一些。
*** 时间
<2017-01-03>
*** 摘抄
。。。愿望，想要给心穿上铠甲。
*** 读后感
在“雪人”案中遍体鳞伤的警探哈利·霍勒辞职前往了香港，躲在一个无人问津的小角落中靠鸦片逃离现实。挪威却出现了新的连环杀手，作为唯一有侦破连环杀人案经验的警探，警方只能想法设法请回他破案，年轻漂亮的女警官卡雅完成了这个任务，却因为警察系统和特殊部门系统的冲突而不能痛快地办案，甚至卡雅都是特殊部门头头的情人。慢慢他们发现了被害人都住过同一间滑雪小屋，事情的真相也一步又一步地逐渐被拨开，最后的真相却只是因为一个自卑的人目睹自己女伴与另一个留有旧隙的人发生了性关系，常年的怨恨一次爆发，导致他引导那名男人做下了这些案行。
不知道有没有科学道理，但是一个地区的人们的气质风格多少会与这个地区的天气气候有所关联，就像热带地区的人们多热情，所以北欧的各种作品总是会有一种难以言说的冷冽感，就像电影《狩猎》，或者“千禧年三部曲”，似乎因为天气，那里的人们会认为人性也会变冷许多。另一方面讲这也是北欧的魅力所在。
** 《一朵桔梗花》4*                                                :[日] 连城三纪彦:
1. 短评
   语言优美，历史感浓厚，有一种独属于日本文化的物哀的衰败美感。
2. 时间
   end：<2017-01-06 周五>
3. 资源
   豆瓣：https://book.douban.com/subject/5269222/
** 《模仿犯》3.5*                                                  :[日]宫部美雪:
*** 短评
相当长的长篇，宫部美雪试图通过一个不那么典型的犯罪案件探索罪犯、指使者、受害人家属、罪犯家属等等人物在杀人事件这种极端条件下的反应和心理活动，想法很好，奈何把握能力稍显不足。
*** 时间
end：<2017-01-17 周二>
*** 资源
豆瓣：https://book.douban.com/subject/1035887/
* 计算机科学
** 《别再迷恋互联网思维》0x					:陶旭骏、陈 平、刘 羽:
1. 短评
   序章读完足矣，互联网本来就只是手段。
2. 时间
   <2016-11-29 周二>
3. 资源
   豆瓣：https://book.douban.com/subject/26856577/
* 财经管理
** 《经济学原来这么有趣 : 颠覆传统教学的18堂经济课》0x                  :钟伟伟:
1. 短评
   真的一点都不有趣，还是应该读教材。
2. 时间
   <2016-11-24 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/22994595/
* 科幻神奇
** 《地铁2033》0x					     :[俄]德米特里•格鲁克夫斯基:
1. 短评
   开头弃，翻译爆炸，完全没法读。
2. 资源
   豆瓣：https://book.douban.com/subject/5385399/
* 西方玄幻
* 武侠仙侠
** 《司藤》3*                                                            :尾鱼:
*** 短评
好看归好看，终究平淡了点，读完留不下太深的印象。
*** 摘抄
1. 只不过谁的情意都不是长久干烧的火，不添柴也就罢了，哪经得起日复一日的水打冰浇？
2. 爱与不爱，差的也就是一个“不”字，一横一撇，一竖一点，当初不会写，谁还一生一世不会写啊。
*** 资源
end：<2017-02-08 周三>
豆瓣：https://book.douban.com/subject/26674263/
* 诗歌散文
* 科学知识
** 《人造恐慌-转基因全球实地考察》0*                                    :袁越:
1. 短评
   开头弃，科普类书籍主观色彩太强烈是不可取的。
2. 资源
   豆瓣：https://book.douban.com/subject/26140658/
* 个人提升
** 《番茄工作法图解 : 简单易行的时间管理方法》0x     :[瑞典] Staffan Nöteberg:
1. 短评
   全部干货都在第一章，剩下的要去试过才知道合适不合适。
2. 时间
   <2016-11-24 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/5916234/
** 《高效能人士的七个习惯（精华版）》0x                         :[美] 史蒂芬·柯维:
1. 短评
   开头弃，算是逻辑还算通顺的浓缩鸡汤？
2. 资源
   豆瓣：https://book.douban.com/subject/1048007/
** 《你所谓的稳定，不过是在浪费生命》0*                                :李尚龙:
1. 短评
   读了两章，实在读不下去了，感情不当自由职业者就不对了吗？
2. 时间
   <2016-12-08 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/26728018/
