#+TITLE:读书记录
* 经典文学
** 《蝇王》 0x							  :(英)威廉·戈尔丁:
    1. 短评
       翻译不喜欢（上海译文出版社 2009-10）。
    2. 时间
       <2016-11-24 周四>
    3. 资源
       豆瓣：https://book.douban.com/subject/4125911/
** 《恐惧》 4x 							 :[奥]斯蒂芬•茨威格:
1. 短评
   与《一个陌生女人的来信》有着相同爽快的阅读体验，很好奇茨威格如何能够写女人写的入木三分。
2. 读后感
   小说的女主角与情人偷情被发现而受到情人“女友”的威胁和敲诈，因而陷入了深深的恐惧之中，甚至想要结束自己的生命，结果最后发现是丈夫设下的局。
   纵然我们很少有人有偷情被发现这样的经历，这份类似的恐惧感依然深深地抓住了我的心，我们或多或少都曾处于过这样的境地，很多时候这份恐惧比事实能对我们造成的伤害还要大的多。
   对于为何会产生这样的行为，小说进行了一些探讨。女主说这种恐惧是出于对最亲密之人的爱，这样的说法多少有些往自己脸上贴金的味道。而在我看来，这种情绪出现的最大原因就是我们很多时候都不能或者说不敢去承受一件事情可能带来的后果，至于不想伤害别人，不过是软弱的借口而已。
3. 完成时间
   <2016-11-30 周三>
4. 资源
   + 豆瓣：https://book.douban.com/subject/10563555/
* 现代文学
** 《没有人给他写信的上校》4x					    :(哥伦比亚)加西亚·马尔克斯:
    1. 读后感
       抛去魔幻现实主义的繁华，淳朴真实的马尔克斯依然有触动人心的力量。
    2. 资源
       豆瓣：[[https://book.douban.com/subject/20392523/]]
    3. 时间
       开始时间：<2016-11-29 周二>
       结束时间：<2016-11-30 周三>
** 《一个背叛日本的日本人》2x					    :(日)松本清张:
    1. 短评       
    2. 读后感
       说实在的，我没有从这本小说中获得什么有用的体会。悬念被标题剧透地丧心病狂，毫无紧张感和悬念感，整体的人物塑造也很苍白，读完后没有哪位人物给我留下了很深的印象，剧情也安排地毫无张力。
    3. 资源
       豆瓣：https://book.douban.com/subject/6848987/
    4. 其他
       原名：《球形的荒野》
*** 《手机里的男朋友 : 方慧首部短篇小说集》                            :方慧:
1. 短评
   开头弃，节奏和文笔不能吸引我。
2. 资源
   豆瓣：https://book.douban.com/subject/26647727/
*** 《我就要你好好的（新版）》                                  :【英】乔乔·莫伊斯:
1. 短评
   爱情这种东西，很多时候并没有我们想的那么有力。
2. 资源
   豆瓣：https://book.douban.com/subject/26683858/
* 网络文学 
** 《贩罪》0x                                                          :三天两觉:
    1. 读后感
     三天两觉有伊坂幸太郎的气质,可惜文笔和格局上还跳脱不了网文的窠臼。
    2. 资源
     豆瓣：https://book.douban.com/subject/26863353/
    3. 时间
     开始时间：<2016-11-29 周二>
     结束时间：<2016-11-29 周二>
* 推理悬疑
** 《替死者说话》0x                                                    :再见萧郎:
    1. 短评
       开头弃，开头悬念设置的不错，但是文笔实在过于朴实，情节也显得很虚浮。
    2. 时间
       开始时间：<2016-11-24 周四>
       结束时间：<2016-11-24 周四>
    3. 资源
       豆瓣：https://book.douban.com/subject/24698542/
** 《别和她说话》0x                                                      :遇瑾:
    1. 短评
       开头弃，文笔差，心理学知识也不严谨。
    2. 资源
       https://book.douban.com/subject/26434548/
* 计算机科学
** 《别再迷恋互联网思维》0x					:陶旭骏、陈 平、刘 羽:
    1. 短评
       序章读完足矣，互联网本来就只是手段。
    2. 时间
       <2016-11-29 周二>
    3. 资源
       豆瓣：https://book.douban.com/subject/26856577/
* 财经管理
** 《经济学原来这么有趣 : 颠覆传统教学的18堂经济课》0x                  :钟伟伟:
    1. 短评
       真的一点都不有趣，还是应该读教材。
    2. 时间
       <2016-11-24 周四>
    3. 资源
       豆瓣：https://book.douban.com/subject/22994595/
* 科幻神奇
** 《地铁2033》0x					     :[俄]德米特里•格鲁克夫斯基:
    1. 短评
       开头弃，翻译爆炸，完全没法读。
    2. 资源
       豆瓣：https://book.douban.com/subject/5385399/
* 西方玄幻
* 武侠仙侠
* 诗歌散文
* 科学知识
* 个人提升
** 《番茄工作法图解 : 简单易行的时间管理方法》0x     :[瑞典] Staffan Nöteberg:
1. 短评
   全部干货都在第一章，剩下的要去试过才知道合适不合适。
2. 时间
   <2016-11-24 周四>
3. 资源
   豆瓣：https://book.douban.com/subject/5916234/
** 《高效能人士的七个习惯（精华版）》0x                         :[美] 史蒂芬·柯维:
1. 短评
   开头弃，算是逻辑还算通顺的浓缩鸡汤？
2. 资源
   豆瓣：https://book.douban.com/subject/1048007/
